version: '3.8'
services:
  node:
    depends_on:
      - db
    build: .
    container_name: node
    env_file: 
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
  db:
    container_name: MySQL
    image: mysql/mysql-server:8.0.32-1.2.11-server
    env_file: 
      - ./.env
    ports:
      - $DB_PORT:$DB_PORT
    restart: always

    
